export const strings = {
  appName: 'Капелюх',
  home: {
    newGame: 'Нова гра',
    rules: 'Як грати',
    settings: 'Налаштування',
    about: 'Про додаток',
    tagline: 'Весела гра для компанії',
    openSettings: 'Відкрити налаштування',
  },
  common: {
    next: 'Далі',
    start: 'Почати',
    back: 'Назад',
    done: 'Готово',
    skip: 'Пропустити',
    understand: 'Зрозуміло',
    placeholder: 'Екран у розробці',
  },
  setup: {
    title: 'Нова гра',
    teamsTitle: 'Команди',
    wordCount: 'Кількість слів',
    turnDuration: 'Час ходу',
    teamCount: 'Команди',
    difficulty: 'Рівень',
    skipPenalty: 'Штраф за пропуск слова',
    skipPenaltyNone: 'Без штрафу',
    skipPenaltyMinusOne: '−1 бал за пропуск',
    difficultyEasy: 'Легкий',
    difficultyMedium: 'Середній',
    difficultyHard: 'Важкий',
    teamPlaceholder: 'Назва команди',
    wordSetNote: 'Один набір слів грається за 3 раунди',
    teamHint: 'Натисни на назву, щоб змінити',
  },
  rounds: {
    elias: 'ЕЛІАС',
    crocodile: 'КРОКОДИЛ',
    association: 'АСОЦІАЦІЯ',
    roundLabel: (n: number, total: number) => `Раунд ${n} з ${total}`,
    teamTurn: 'Хід команди',
    eliasHint: 'Поясни слова, не називаючи саме слово',
    crocodileHint: 'Показуй слово жестами та мімікою',
    associationHint: 'Пояснюй одним асоціативним словом',
    forbidden: 'ЗАБОРОНЕНО',
    eliasForbidden: ['жести та міміка', 'однокореневі слова', 'переклад іноземною'],
    crocodileForbidden: [
      'вимовляти слова та будь-які звуки',
      'вказувати на людей та предмети',
      'використовувати предмети',
    ],
    associationForbidden: ['однокореневі слова', 'міміку та жести', 'більше одного слова'],
    carryOverContinues: (name: string) => `Команда ${name} продовжує`,
    carryOverTimeLeft: (sec: number) => `Залишилось ${sec} сек`,
  },
  turn: {
    guess: 'Вгадав',
    skip: 'Пропустити',
    wordForAll: 'СЛОВО ДЛЯ ВСІХ',
    pause: 'Пауза',
  },
  pause: {
    title: 'Гру зупинено',
    round: (name: string) => `Тур: ${name}`,
    team: (name: string) => `Команда: ${name}`,
    exit: 'Вийти',
    resume: 'Продовжити',
  },
  award: {
    title: 'Кому віддати слово?',
    nobody: 'Ніхто не вгадав',
  },
  review: {
    timeUp: 'Час вичерпано',
    hatEmpty: 'Капелюх пустий',
    pointsAwarded: 'Нараховано балів',
    confirmStop: 'Завершити матч?',
    emptyTurn: 'На жаль, ваша команда не вгадала жодного слова в цьому раунді.',
    nextTeam: 'Наступна команда',
    nextRound: 'Наступний тур',
    matchResults: 'Результати гри',
  },
  results: {
    matchComplete: 'Гру завершено',
    statisticTitle: 'Статистика гри',
    congrats: 'Вітаємо команди!',
    playAgain: 'Зіграти ще!',
    statSkip: 'Пропустити',
    statNext: 'Далі',
    tableRound: 'Тур',
    tableTotal: '🏅',
    stats: {
      fastestGuess: (word: string, seconds: number) =>
        `Найшвидше вгадали слово «${word}» — лише за ${seconds} секунд`,
      mostSkippedWord: (word: string, count: number) =>
        `Слово «${word}» пропускали найчастіше — ${count} разів`,
      bestTurn: (teamName: string, count: number) =>
        `Найпродуктивніший хід: Команда «${teamName}» відгадала ${count} слів`,
    },
  },
  settings: {
    title: 'Налаштування',
    sound: 'Звук',
    soundDescription: 'Звукові ефекти під час гри',
    haptics: 'Вібрація',
    hapticsDescription: 'Тактильний відгук на дії',
    sentry: 'Звіти про збої',
    sentryDescription: 'Анонімні звіти для покращення стабільності',
    skipPenalty: 'Штраф за пропуск слова',
    skipPenaltyDescription: '−1 бал команді за кожне пропущене слово',
    about: 'Про гру',
    play: 'Грати',
  },
  about: {
    title: 'Про гру',
    description:
      '«Капелюх» — офлайн party game для iPhone. Один пристрій, три тури, одна колода слів. Без реклами, без акаунтів, без інтернету.',
    version: (version: string) => `Версія ${version}`,
    privacy: 'Політика конфіденційності',
  },
  privacy: {
    title: 'Політика конфіденційності',
    headerTitle: 'Конфіденційність',
    updated: 'Останнє оновлення: червень 2026',
    sections: [
      {
        title: 'Загальні положення',
        body: '«Капелюх» — офлайн-гра. Ми не збираємо персональні дані, не створюємо акаунти і не продаємо інформацію третім сторонам.',
      },
      {
        title: 'Дані на пристрої',
        body: 'Налаштування гри, активна сесія та історія матчів зберігаються лише на вашому iPhone. Ви можете видалити їх, видаливши застосунок.',
      },
      {
        title: 'Звіти про збої',
        body: 'За вашою згодою (увімкнено в налаштуваннях) застосунок може надсилати анонімні звіти про збої через Sentry. Звіти не містять імен команд, слів чи іншого ігрового контенту.',
      },
      {
        title: 'Контакти',
        body: 'Питання щодо конфіденційності: manhengest@gmail.com',
      },
    ],
  },
  rules: {
    skipAll: 'Все зрозуміло',
    wantToPlay: 'Хочу грати!',
    steps: [
      {
        title: 'Про що ця гра?',
        body: '«Капелюх» — офлайн гра для компанії. Одна команда пояснює слова, інші вгадують. Той самий набір слів проходить три тури з різними правилами.',
        tipLabel: 'УВАГА',
        tip: 'Один телефон передається між командами — не показуй слово іншим гравцям!',
      },
      {
        title: 'Як пояснювати?',
        body: 'Три тури на одних словах: Еліас (слова), Крокодил (жести), Асоціація (одне слово).',
        tipLabel: 'ПОРАДА',
        tip: 'Чим знайоміші слова до третього туру, тим веселіше!',
      },
      {
        title: 'Хто перемагає?',
        body: 'За кожне вгадане слово +1 бал. Пропуск може коштувати −1, якщо це увімкнено. Перемагає команда з найбільшою сумою балів.',
        tipLabel: 'УВАГА',
        tip: 'Якщо час вийшов на слові — воно стає «Словом для всіх».',
      },
      {
        title: 'Підготовка до гри',
        body: 'Збери друзів, поділись на команди (мінімум 2 команди по 2 людини), обери налаштування — і грай!',
        tipLabel: 'ПОРАДА',
        tip: 'Краще грати в тихому колі, щоб усі чули пояснювача.',
      },
    ],
  },
} as const;

export const ROUND_DISPLAY_NAMES = {
  elias: strings.rounds.elias,
  crocodile: strings.rounds.crocodile,
  association: strings.rounds.association,
} as const;
